### ISSUE TITLE
An option to exclude some asseblies

### ISSUE THREAD

**Issue by FixRM** [ravibpatel/ILRepack.Lib.MSBuild.Task#1]
Hi. I'm getting the error "Failed to resolve assembly" during merge. The problem is that I don't need this assembly to be merged as it will be available in target environment.

**Comment by ravibpatel** [comment]
@FixRM Did you try manually providing assemblies to merge?

**Comment by FixRM** [comment]
Yes, all my assemblies are listed in project file as <InputAssemblies Include="$(OutputPath)\ExampleAssemblyToMerge1.dll" />. No wildcards or library paths used.

The error occurrences then third target system SDK assembly is not listed there. This SDK assembly shouldn't be merged as target system use reflection to initialize plugin-classes from my assembly.

**Comment by ravibpatel** [comment]
@FixRM Looks like an issue with ILRepack.Lib. You can ask for the workaround on [ILRepack](https://github.com/gluck/il-repack) project page.

**Comment by FixRM** [comment]
Thanks

**Comment by FixRM** [comment]
You were right it was issue in ILRepack itself. Setting /lib: (or LibraryPath) parameter fixed the problem. Thanks again
