### ISSUE TITLE
Default ILRepack target not run when doing a Rebuild

### ISSUE THREAD

**Issue by jairbubbles** [ravibpatel/ILRepack.Lib.MSBuild.Task#11]
It's declared like this:
```xml
<Target Name="ILRepack" AfterTargets="Build" ..>
```

I think it should be:
```xml
<Target Name="ILRepack" AfterTargets="Build;Rebuild" ..>
```
Thx!

**Comment by ravibpatel** [comment]
@jairbubbles Thanks for reporting it. I will fix it asap.

**Comment by ravibpatel** [comment]
@jairbubbles I tried using Rebuild and it seems to execute ILRepack task.

[http://prntscr.com/knern5](url)

**Comment by jairbubbles** [comment]
I'll look into it a bit more.
