### ISSUE TITLE
ILRepack.Lib.MSBuild.Task does not work on Linux

### ISSUE THREAD

**Issue by mogawinch** [ravibpatel/ILRepack.Lib.MSBuild.Task#17]
Hello,
I would like to use ILRepack MSBuild Task on Linux, but having a dependency on **Microsoft.Build.Utilities.v4.0** make it impossible to use it.

```
error MSB4062: The "ILRepack" task could not be loaded from the assembly /root/.nuget/packages/ilrepack.lib.msbuild.task/2.0.16/build/ILRepack.Lib.MSBuild.Task.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

There is a plan to make this NuGet package Linux compatible?

Thank you,
Marc-André

**Comment by Azhe403** [comment]
Not only Linux. on Windows too 

![kb9kKBuAEg](https://user-images.githubusercontent.com/17938038/81471504-b3690d00-921b-11ea-9ff7-3fae32592642.png)

**Comment by fiskra** [comment]
any update on this ?

**Comment by ravibpatel** [comment]
Can you try latest version? It should fix the issue.
