### ISSUE TITLE
Problem with TargetPlatformVersion parameter

### ISSUE THREAD

**Issue by FixRM** [ravibpatel/ILRepack.Lib.MSBuild.Task#2]
I have to set very specific target platform version to avoid reference hell in product environment. I can archive this by passing /targetplatform:v4,C:\Windows\Microsoft.NET\Framework\v4.0.30319 parameter via command line.

Unfortunately if I set TargetPlatformVersion="v4,C:\Windows\Microsoft.NET\Framework\v4.0.30319" in config I get "Failed to find target platform 'v4,C:\Windows\Microsoft.NET\Framework\v4.0.30319' in 'C:\Windows\Microsoft.NET\Framework"

p.s. Folder exist.

**Comment by ravibpatel** [comment]
@FixRM Try passing only "v4".

**Comment by FixRM** [comment]
I tried. It doesn't work in my case as I have a bloody mess of legacy DI/Ninject code together with my code. Passing "v4" cause run time errors like "System.IO.FileNotFoundException: Could not load file or assembly 'System.Core, Version=2.0.5.0" and others. Passing v4,C:\Windows\Microsoft.NET\Framework\v4.0.30319 (via CMD) work as expected.

p.s. Project

**Comment by FixRM** [comment]
I looked through task and ILRepack code and it looks like the problem is in ILRepack once again. Sorry for taking your time.

**Comment by FixRM** [comment]
Hello. I find that API use TargetPlatformVersion version works together with TargetPlatformDirectory parameter (but there is one parameter in command line interface). Can you please add support for it?

p.s. I tried to create Pull request but failed.  I'm new with Git/Github so not sure if I'm doing something wrong or I don't have access rights

**Comment by ravibpatel** [comment]
@FixRM I will do it asap. If you want to do it then you need to Fork the repo by clicking Fork on the top right. Then you can add the changes to your forked repo. You can create pull request after that.

**Comment by FixRM** [comment]
Thank you for explanation. As it takes only 2 lines of code I'll wait for you if you don't mind. :) NuGet package will be updated automatically?

**Comment by ravibpatel** [comment]
@FixRM No Problem. I will update the NuGet package too.

**Comment by ravibpatel** [comment]
@FixRM Updated NuGet package.

**Comment by FixRM** [comment]
@ravibpatel Thanks a lot. Now it works as expected and I finally can migrate from ILMerge!
