### ISSUE TITLE
Could you please provide a new release?

### ISSUE THREAD

**Issue by Aldomat** [ravibpatel/ILRepack.Lib.MSBuild.Task#24]
Thanks in advance und best regards,

Carsten

**Comment by ravibpatel** [comment]
I release the new version. It will be available soon.

**Comment by jstevenson72** [comment]
I'm not able to get the **CleanReferenceCopyLocalPaths** Target to happen.  I've enabled verbose logging, and don't see anything related to it.

I've setup both a ILRepack.Config.props file and an ILRepack.targets file within my Project.

It merges all of the correct DLLs but does not cleanup the source .dlls.  Could anyone help me?
