### ISSUE TITLE
dotnet build not working

### ISSUE THREAD

**Issue by theKBro** [ravibpatel/ILRepack.Lib.MSBuild.Task#29]
if using dotnet build instead of msbuild there is an error that Microsoft.Build.Utilities.v4.0 cannot be found!

The "ILRepack" task could not be loaded from the assembly ...\.nuget\packages\ilrepack.lib.msbuild.task\2.0.18\build\ILRepack.Lib.MSBuild.Task.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

**Comment by nils-a** [comment]
I'm guessing it's the same problem that was discussed in https://github.com/dotnet/msbuild/issues/2111 so maybe the solution is in there, too.

**Comment by nils-a** [comment]
probably related to #17

**Comment by RobertAcksel** [comment]
related to #28

**Comment by jairbubbles** [comment]
Switching to this fork (https://github.com/Alexx999/ILRepack.Lib.MSBuild.Task) does fix the issue but it's missing some commits from there.

The NuGet package is https://www.nuget.org/packages/ILRepack.Lib.MSBuild/.

**Comment by KirillOsenkov** [comment]
The recent version should support this properly.
