### ISSUE TITLE
Where do we put the reference to the key

### ISSUE THREAD

**Issue by TomT15** [ravibpatel/ILRepack.Lib.MSBuild.Task#35]
Im trying to understand the following:
![image](https://user-images.githubusercontent.com/47607041/191845365-15f09165-ad2b-444b-babc-808286d39845.png)
The documentation does not specifically say where i should put this reference so i tried following directions from this documentation but have been unable to get the key to work properly
https://learn.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name

**Comment by ravibpatel** [comment]
If you are using the same config, then the key file should be present in your project directory where your .csproj and ILRepack.Config.props file resides.

**Comment by TomT15** [comment]
I did try adding a ILRepack.Config.props to the project file and noticed no
different when building and deploying as it still says that there is not a
key assigned to it. I will try more Monday

Thomas Tramp

**Comment by mamift** [comment]
> I did try adding a ILRepack.Config.props to the project file and noticed no different when building and deploying as it still says that there is not a key assigned to it. I will try more Monday Thomas Tramp

Thomas, it worked for me by putting an `KeyFile` attribute on the `<ILRepack>` element:

```XML
    <ILRepack Parallel="true" Internalize="true" InternalizeExclude="@(DoNotInternalizeAssemblies)" InputAssemblies="@(InputAssemblies)" TargetKind="Dll" OutputFile="$(OutputPath)\$(AssemblyName).dll" 
    KeyFile="$(ProjectDir)key.snk" />
```

The README.md file seems to give incorrect instructions.

**Comment by ravibpatel** [comment]
As mentioned in the doc, "This configuration option only applies if you are using the default targets file provided in NuGet package." So if you are using custom targets file then it won't work.
