### ISSUE TITLE
Internalize not working with 2.0.22

### ISSUE THREAD

**Issue by antineutrino** [ravibpatel/ILRepack.Lib.MSBuild.Task#44]
The following
![image](https://github.com/ravibpatel/ILRepack.Lib.MSBuild.Task/assets/1374766/b754a21e-289f-4d5c-b6fc-593926ac4486)
generates this Assembly
![image](https://github.com/ravibpatel/ILRepack.Lib.MSBuild.Task/assets/1374766/11964eb7-44df-49b6-9b51-29ed8e525fa6)

It worked with 2.0.18.

**Comment by KirillOsenkov** [comment]
There's been an intentional change of behavior where if a class is reachable by the public API of the main assembly, it will no longer be internalized, to prevent inconsistencies in access modifiers. It seems that InvalidDataException may be used by some other public API?

Also, internalize doesn't internalize types in the main assembly. This is also by design.

**Comment by KirillOsenkov** [comment]
I see some other types in the Persistence namespace such as ConnectionInfo, IDbTracer, etc. seem to be internal.

**Comment by sbe-schleupen** [comment]
The public types are not used anywhere in the solution where the repacking is happening. Is there some special behavior when it comes to exception types?
![image](https://github.com/ravibpatel/ILRepack.Lib.MSBuild.Task/assets/74196732/208bc734-aa55-46f8-a1ce-0b5d21d3755a)

**Comment by KirillOsenkov** [comment]
Hard to say without having access to your assemblies to investigate.

The source code is here if you want to debug:
https://github.com/gluck/il-repack/blob/master/ILRepack/Steps/PublicTypesFixStep.cs

**Comment by antineutrino** [comment]
[ILRepackBug.zip](https://github.com/ravibpatel/ILRepack.Lib.MSBuild.Task/files/13857480/ILRepackBug.zip)

The problem can be reproduced with this solution. Exception types seem to have some special behavior.

**Comment by antineutrino** [comment]
If I understand the code correctly, the issue seems to be this code:
![image](https://github.com/ravibpatel/ILRepack.Lib.MSBuild.Task/assets/1374766/4b04b132-5b2e-4311-b601-756fa1a2c5ef)
https://github.com/gluck/il-repack/commit/0ce59b14493dae9772c6c677c043baa8775748dd#diff-5c1acbbbdc2379afb7f358e73fd668909104afaa4fd792bee05b481000647abe

Serializable types (like exceptions) are always not internalized.

A way to get the old behavior would be nice.

**Comment by KirillOsenkov** [comment]
How's this?

https://github.com/gluck/il-repack/commit/175f15b72225aa3b15d80e9a7d4360be49059222

**Comment by antineutrino** [comment]
Hi,
I think this works in principle. 

But there seems to be an issue when parsing the command line.
![image](https://github.com/ravibpatel/ILRepack.Lib.MSBuild.Task/assets/1374766/eff19d36-3861-4e06-a792-089be52f5282)

Without this line the new cli argument is in the input assemblies list
![image](https://github.com/ravibpatel/ILRepack.Lib.MSBuild.Task/assets/1374766/c1cff47d-b0c9-4635-9cc1-c2eb9b0fbde2)
This leads to an error later on.

**Comment by KirillOsenkov** [comment]
interesting, thanks for testing it! I'll look at the fix tomorrow, it's actually surprising behavior that I might want to fix

**Comment by KirillOsenkov** [comment]
My apologies once again! I wasn't very experienced with this command line API. Found the problem here:
https://github.com/gluck/il-repack/commit/b8986b8c5a768de2769c3e767cc7e171355613d8

How's this?

**Comment by antineutrino** [comment]
Looks good to me.

**Comment by antineutrino** [comment]
Any plans to release a new BuildTask version?
