### ISSUE TITLE
Nuget API key in appveyor.yml file?

### ISSUE THREAD

**Issue by ryannewington** [ravibpatel/ILRepack.Lib.MSBuild.Task#45]
Is this a valid Api key?

https://github.com/ravibpatel/ILRepack.Lib.MSBuild.Task/blob/2cabc0e6e5cc0a4b2cab75afe3cd706fbf585caf/appveyor.yml#L25C15-L25C79

**Comment by ravibpatel** [comment]
It is encrypted, so there is nothing to worry about.
