### ISSUE TITLE
Should the NuGet package be marked as a development dependency?

### ISSUE THREAD

**Issue by Numpsy** [ravibpatel/ILRepack.Lib.MSBuild.Task#47]
Hi,
I tried attaching the ILRepack.Lib.MSBuild.Task nuget package to a project of mine to test, and noticed that my created nuget package has a dependency on ILRepack.Lib.MSBuild.Task itself.

I can add a ```PrivateAssets="all"``` to the PackageReference in my project myself to avoid it, but I wonder if nuget package here should maybe have a ```<developmentDependency>true</developmentDependency>``` in it so that gets done automatically?

**Comment by ravibpatel** [comment]
I tried it, and it adds PrivateAssets="all" without specifying the developmentDependency in nuspec for me.

**Comment by Numpsy** [comment]
Hmm, not sure then. I was F# project with central package version management enabled at the time, I'll try it with something more minimal to check.
This was with Visual Studio 2022 17.8.3 for the record.

**Comment by ravibpatel** [comment]
I added it because it is a developmentDependency after all. Thanks for reporting.

**Comment by Numpsy** [comment]
Thanks, I tried it with 2.0.26 and it's setting PrivateAssets itself now.
