### ISSUE TITLE
Repacking Harmony in Debug mode fails

### ISSUE THREAD

**Issue by pardeike** [ravibpatel/ILRepack.Lib.MSBuild.Task#49]
Hi,

my open source project [Harmony](https://github.com/pardeike/Harmony) uses this task to pack its "Fat" releases. It works fine but we discovered that the "DebugFat" release does not work on .NET 5 or newer. Packing itself isn't the problem because ReleaseFat works just fine.

The problem is very easy to replicate by cloning the project (master) and running tests for DebugFat and ReleaseFat.

There is an active discussion going on on my discord server where the guys from the MonoMod.Core project (a dependency Harmony has) discuss that this is related to them using some function pointer [here](https://github.com/MonoMod/MonoMod/blob/reorganize/src/MonoMod.Core/Platforms/Runtimes/Core21Runtime.cs#L115) which matches the exception I get when running/testing DebugFat:

```
System.TypeLoadException : Could not load type 'CORINFO_METHOD_INFO' from assembly 'System.Runtime.Serialization.Formatters, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```
which is also randomly giving other assemblies (so not related to System.Runtime.Serialization.Formatters at all).

Quote from @nike4613 in the discord: 
- InvokeCompileMethod there is a property which returns a function pointer, which is immediately invoked
- this is emitted as a calli
- you'll notice, one of the parameters is a V21.CORINFO_METHOD_INFO*
- i think that the repacker is messing up the calli signature in exactly the same way that monomod's calli emitter was
- so one way or another, the sig asks for CORINFO_METHOD_INFO, but that somehow has the wrong 'context' token 

If you want to discuss this issue, you are welcome to temporarily join my [discord server](https://discord.gg/xXgghXR). The channel is called `harmony-contributors`.

**Comment by KirillOsenkov** [comment]
Hi, big fan of Harmony. Very busy week but I'll try to get to it this weekend.

**Comment by pardeike** [comment]
No worries. Glad you respond so fast ☺️

**Comment by KirillOsenkov** [comment]
The upstream bug is fixed in 2.0.29: https://github.com/gluck/il-repack/issues/355

https://www.nuget.org/packages/ILRepack/2.0.29

Here's the PR to update ILRepack.Lib.MSBuild.Task to 2.0.29:
https://github.com/ravibpatel/ILRepack.Lib.MSBuild.Task/pull/50

**Comment by KirillOsenkov** [comment]
After this is merged and published, we can bump Harmony to 2.0.29 and validate the fix.

**Comment by ravibpatel** [comment]
Merged and published. Thanks for fixing it so fast.

**Comment by pardeike** [comment]
works like a charm
