### ISSUE TITLE
Repack Drop Attributes not dropped

### ISSUE THREAD

**Issue by roguesaloon** [ravibpatel/ILRepack.Lib.MSBuild.Task#55]
Specified attributes are not dropped when using the `RepackDropAttribute` property as part of the MSBuild task. This persumably worked at some point (when it was added?), but no longer works with the latest version of ILRepack due to the way the backend is structured (uses `RepackDropAttributes` HashSet parsed from passed commandline option). I have created and tested a fix for this issue, that aligns closely with the commandline parser in `RepackOptions` (from IL Repack).

**Comment by roguesaloon** [comment]
Have raised PR to fix this issue:
https://github.com/ravibpatel/ILRepack.Lib.MSBuild.Task/pull/56

**Comment by ravibpatel** [comment]
Thanks for the fix. I pushed the updated package to NuGet it should be available soon.
