### ISSUE TITLE
LibraryPath works fine in Debug, but is empty in Release

### ISSUE THREAD

**Issue by van800** [ravibpatel/ILRepack.Lib.MSBuild.Task#6]
My project is this one
https://github.com/JetBrains/resharper-unity/blob/master/unity/JetBrains.Rider.Unity.Editor/EditorPlugin/EditorPlugin.csproj

**Comment by ravibpatel** [comment]
@van800  I tested your project and for release and debug both i get "resharper-unity\unity\JetBrains.Rider.Unity.Editor\EditorPlugin\..\bin\net35\" in LibraryPath.

**Comment by van800** [comment]
@ravibpatel As far as I understood the problem. [Targets file](https://github.com/ravibpatel/ILRepack.Lib.MSBuild.Task/blob/master/ILRepack.Lib.MSBuild.Task/ILRepack.Lib.MSBuild.Task.targets) calls ILRepack with AfterBuild condition
 <Target Name="AfterBuild" Condition="'$(Configuration)' == 'Release'">
And there is no good way to override it.

So for me Debug worked fine, since my task was called, but in release ILRepack task from your targets was called.

In master I have already workarounded the problem, by removing referencing your nuget.
Please use this state of project to see the problem.
https://github.com/JetBrains/resharper-unity/blob/08b67f7aa4b516aed9d2f2d057ad75e77b06353f/unity/JetBrains.Rider.Unity.Editor/EditorPlugin/EditorPlugin.csproj

Thanks!

**Comment by ravibpatel** [comment]
@van800  You are right default targets file is not great for every situation. I tried the master. But the link you gave me doesn't import targets file provided with NuGet package then how release task from that targets file is being called?

**Comment by van800** [comment]
@ravibpatel In "new csproj" when nuget is referenced, targets are referenced behind the scenes.
With help of this tool https://github.com/KirillOsenkov/MSBuildStructuredLog I understood, what happened.

**Comment by van800** [comment]
Left is debug, right - release.
![image](https://user-images.githubusercontent.com/1482681/36246477-4ba2b288-1230-11e8-8a91-00e74f671ada.png)

**Comment by ravibpatel** [comment]
@van800 If I use following targets file it can solve your issue. It checks for "ILRepack.targets" file in Project directory. If it is present in the directory then it uses that targets file otherwise it uses default targets file that comes with NuGet package. I tried it on my end and it works perfectly. Can you confirm it?

```xml
<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <UsingTask AssemblyFile="$(MSBuildThisFileDirectory)ILRepack.Lib.MSBuild.Task.dll" TaskName="ILRepack" />
	<Import Project="$(ProjectDir)ILRepack.targets" Condition="Exists('$(ProjectDir)ILRepack.targets')" />
	<Target Name="AfterBuild" Condition="'$(Configuration)' == 'Release' and !Exists('$(ProjectDir)ILRepack.targets')">
		<ItemGroup>
			<InputAssemblies Include="$(OutputPath)$(TargetName)$(TargetExt)"/>
			<InputAssemblies Include="$(OutputPath)*.dll" Exclude="$(OutputPath)$(TargetName)$(TargetExt)"/>
		</ItemGroup>

		<ILRepack
			Parallel="true"
			DebugInfo="true"
			AllowDuplicateResources="false"
			InputAssemblies="@(InputAssemblies)"
			TargetKind="SameAsPrimaryAssembly"
			OutputFile="$(OutputPath)$(TargetName)$(TargetExt)"
		/>
	</Target>
	<Target 
		AfterTargets="AfterBuild"
		Name="CleanReferenceCopyLocalPaths"
		Condition="'$(Configuration)' == 'Release' and !Exists('$(ProjectDir)ILRepack.targets')">
		<Delete Files="@(ReferenceCopyLocalPaths->'$(OutDir)%(DestinationSubDirectory)%(Filename)%(Extension)')" />
		<ItemGroup>
			<Directories Include="$([System.IO.Directory]::GetDirectories('$(OutDir)%(DestinationSubDirectory)', '*', System.IO.SearchOption.AllDirectories))" />
			<Directories>
				<Files>$([System.IO.Directory]::GetFiles("%(Directories.Identity)", "*", System.IO.SearchOption.AllDirectories).get_Length())</Files>
			</Directories>
		</ItemGroup>        
		<RemoveDir Directories="@(Directories)" Condition="%(Files)=='0'" />
	</Target>
</Project>
```

Add ILRepack.targets file in your Project to make it work. In your case it should be as shown below.

```xml
<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Target Name="ILRepack" AfterTargets="Build">
		<ItemGroup>
		  <InputAssemblies Include="$(OutputPath)/$(AssemblyName).dll" />
		  <InputAssemblies Include="../lib/*.dll" />
		</ItemGroup>
		<ItemGroup>
		  <SearchDirectories Include="$(OutputPath)" />
		</ItemGroup>
		<ILRepack Parallel="true" Internalize="true" DebugInfo="true" InputAssemblies="@(InputAssemblies)" LibraryPath="@(SearchDirectories)" OutputFile="../../Assets/Plugins/Editor/JetBrains/$(AssemblyName).Repacked.dll" />
	</Target>
</Project>
```

**Comment by van800** [comment]
I confirm, that it works.

**Comment by ravibpatel** [comment]
@van800 I will update the NuGet package soon with these changes.

**Comment by ravibpatel** [comment]
@van800 New package uses "ILRepack" as Target name so make sure you change your Target name to something else in your "ILRepack.targets" file.
