### ISSUE TITLE
ILRepack.targets file should always be imported whatever the configuration

### ISSUE THREAD

**Issue by jairbubbles** [ravibpatel/ILRepack.Lib.MSBuild.Task#7]
ILRepacking in Debug configuration can be useful to debug behavior introduced by repacking.

**Comment by ravibpatel** [comment]
@jairbubbles  I will fix it in next version.

**Comment by jairbubbles** [comment]
Awesome!

**Comment by jairbubbles** [comment]
I think it's ok in latest version.
